name: Deploy Preview to Vercel

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - ".github/workflows/**"
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip-deploy]')"
    environment:
      name: Preview
      url: ${{ steps.vercel-deploy.outputs.preview-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@16e87c0a08142b0d0d33b76aeaf20823c381b9b9 # v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
