name: Deploy Preview to Vercel

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - ".github/workflows/**"
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip-deploy]')"
    environment:
      name: Preview
      url: ${{ steps.vercel-deploy.outputs.preview-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v41.1.4
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
